name: '🐛 Documentation Bug Report'
description: 'Report an issue or incorrect information in Gland documentation'
labels: ['documentation', 'needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## 🚨 Before Submitting a Documentation Bug Report

        Thank you for helping us improve Gland documentation! Before submitting, please:

        - Check if a similar issue already exists in the [issue tracker](../issues)
        - Ensure that the issue still exists on the latest version of the documentation
        - Provide a clear description of the problem and any suggested improvements

        For general questions, please use:
        - [Stack Overflow](https://stackoverflow.com/questions/tagged/gland) with the `gland` tag

        ---

  - type: checkboxes
    attributes:
      label: 'Prerequisites'
      description: 'Please confirm the following before submitting your issue'
      options:
        - label: "I have searched for similar issues and couldn't find a solution"
          required: true
        - label: 'I have checked the latest version of the documentation and the issue still exists'
          required: true
        - label: 'I have checked the official repository for any relevant changes'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Current Issue'
      description: 'Describe the incorrect or unclear documentation'
      placeholder: 'The documentation states that X works like Y, but actually...'

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Expected Information'
      description: 'Provide a clear description of what should be stated in the documentation'
      placeholder: 'The documentation should mention...'

  - type: input
    attributes:
      label: 'Affected Documentation Page'
      description: 'Provide the URL of the affected documentation page'
      placeholder: 'https://glandjs.github.io/docs/'

  - type: textarea
    attributes:
      label: 'Suggested Fix (Optional)'
      description: 'If you know how to improve the documentation, please suggest a fix'
      placeholder: 'The correct explanation would be...'

  - type: textarea
    attributes:
      label: 'Additional Context'
      description: 'Add any other context, screenshots, or links that might help understand the issue'
