name: '📝 Documentation Improvement'
description: 'Submit an improvement or enhancement to the Gland documentation'
labels: ['documentation', 'enhancement']
body:
  - type: markdown
    attributes:
      value: |
        ## 🛠️ Before Submitting a Documentation Improvement

        Thank you for helping us enhance Gland's documentation! Before submitting, please:

        - Check if the enhancement has been suggested before
        - Consider the current structure and language of the documentation
        - Provide clear examples or clarifications

        ---

  - type: checkboxes
    attributes:
      label: 'Prerequisites'
      description: 'Please confirm the following before submitting your improvement'
      options:
        - label: 'I have read the documentation carefully'
          required: true
        - label: 'I have suggestions that improve clarity or structure'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Improvement Description'
      description: 'Describe the improvements or enhancements you would like to make'
      placeholder: 'The documentation could be improved by ...'

  - type: textarea
    attributes:
      label: 'Example (Optional)'
      description: 'If applicable, provide an example or suggestion for how the documentation could be enhanced'
      placeholder: 'Here is an example of how to improve ...'

  - type: textarea
    attributes:
      label: 'Additional Context'
      description: 'Provide any additional information or suggestions'
