name: '✨ Feature Request'
description: 'Submit a new feature request for Gland'
labels: ['feature request', 'needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Before Submitting a Feature Request

        Thank you for considering contributing to Gland! Before submitting, please:

        - Check if a similar feature request already exists in the [issue tracker](../issues)
        - Describe the feature and how it would benefit the project
        - Provide any context or use cases for the feature

        ---

  - type: checkboxes
    attributes:
      label: 'Prerequisites'
      description: 'Please confirm the following before submitting your feature request'
      options:
        - label: 'I have searched for similar feature requests'
          required: true
        - label: 'I have considered how the feature would be implemented'
          required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: 'Feature Description'
      description: 'Provide a clear and concise description of the feature'
      placeholder: 'I would like Gland to support ...'

  - type: textarea
    attributes:
      label: 'Use Cases'
      description: 'Explain how this feature will be used or what problems it will solve'
      placeholder: 'This feature would help by ...'

  - type: textarea
    attributes:
      label: 'Additional Context'
      description: 'Add any other context, screenshots, or links that might help explain the feature request'
